config/routes.rb
Rails.application.routes.draw do
  resources :news_topic_comments, :only => [:create]
  get 'news_topic_comments/:news_topic_id' => 'news_topic_comments#show_news_topic_comments',
      as: :show_news_topic_comments
  get 'like_news_topic/:news_topic_id' => 'news_topic_comments#like_news_topic', as: :like_news_topic

  get 'news' => 'news_page#index'
  get 'news/:news_topic_id' => 'news_page#show_news_topic', as: :show_news_topic
  get 'show_more_news_topic/:last_topic_id' => 'news_page#show_more_news_topic', as: :show_more_news_topic

  resources :news_topics

  post 'upload_news_topic_image' => 'news_topics#upload_news_topic_image'
  patch 'upload_news_topic_image' => 'news_topics#upload_news_topic_image'
  post 'preview_news_topic' => 'news_topics#preview_news_topic'

  get 'news_topics/show_more_news_topic/:last_topic_id' => 'news_topics#show_more_news_topic',
      as: :news_show_next_topic

  devise_for :users

  root 'news_page#index'

end

app/models/news_topic.rb
class NewsTopic < ActiveRecord::Base
  belongs_to :creator, :class_name => 'User'
  has_many :news_topic_images
  has_many :news_topic_comments
  has_many :news_topic_user_likes

  scope :top_news, -> { where(top_news: true) }

  def user_liked_this(user_id)
    NewsTopicUserLike.where(
        'news_topic_id = ? and user_id = ?', self.id, user_id
    ).exists?
  end
end

app/controllers/news_topics_controller.rb
class NewsTopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_user_role
  before_action :set_news_topic, :only => [:show, :edit, :update, :destroy]

  # GET /news_topics
  # GET /news_topics.json
  def index
    @news_main_topics = NewsTopic.includes(:creator).order('id DESC').limit(10)
    @top_news = NewsTopic.top_news.order('id DESC').limit(10)
  end

  def show_more_news_topic
    @news_topics = NewsTopic.includes(:creator).where(
        'news_topics.id < ?', params[:last_topic_id].to_i
    ).order('news_topics.id DESC').limit(10)
  end

  # GET /news_topics/new
  def new
    @news_topic = NewsTopic.new
  end

  # GET /news_topics/1/edit
  def edit
    @news_topic.context.gsub!('</br>', "\n")
    @news_topic.short_context.gsub!('</br>', "\n")
  end

  # POST /upload_news_topic_image
  def upload_news_topic_image
    @news_topic_image = NewsTopicImage.new
    @news_topic_image.topic_image = params[:topic_image_upload]
    @news_topic_image.save
  end

  # GET /preview_news_topic
  def preview_news_topic
    @news_topic_context = params[:news_topic_context]
    @news_topic_context.gsub!("\n", '</br>')
    @news_topic_short_context = params[:news_topic_short_context]
    @news_topic_short_context.gsub!("\n", '</br>')
  end

  # POST /news_topics
  # POST /news_topics.json
  def create
    @news_topic = NewsTopic.new(news_topic_params)
    @news_topic.context.gsub!("\n", '</br>')
    @news_topic.short_context.gsub!("\n", '</br>')
    @news_topic.creator = current_user

    respond_to do |format|
      if @news_topic.save
        format.html { redirect_to news_topics_path, :notice => 'News topic was successfully created.' }
        format.json { render :show, :status => :created, :location => @news_topic }
      else
        format.html { render :new }
        format.json { render :json => @news_topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_topics/1
  # PATCH/PUT /news_topics/1.json
  def update
    news_topic_params[:context].gsub!("\n", '</br>')
    news_topic_params[:short_context].gsub!("\n", '</br>')

    respond_to do |format|
      if @news_topic.update(news_topic_params)
        format.html { redirect_to news_topics_path, :notice => 'News topic was successfully updated.' }
        format.json { render :show, :status => :ok, :location => @news_topic }
      else
        format.html { render :edit }
        format.json { render :json => @news_topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /news_topics/1
  # DELETE /news_topics/1.json
  def destroy
    @news_topic.destroy
    respond_to do |format|
      format.html { redirect_to news_topics_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_news_topic
    @news_topic = NewsTopic.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def news_topic_params
    params.require(:news_topic).permit(:title, :context, :short_context, :top_news)
  end

  def verify_user_role
    redirect_to root_path if current_user.role != User::ADMIN_USER
  end
end

app/helpers/news_topics_helper.rb
module NewsTopicsHelper
end

app/views/news_topics/_form.html.erb
<%= form_for(@news_topic) do |f| %>
    <% if @news_topic.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@news_topic.errors.count, 'error') %> prohibited this news_topic from being saved:</h2>

          <ul>
            <% @news_topic.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.text_field :title, :placeholder => 'Title' %>
    </div>
    <div class="field">
      <div id="text_bold" class="font_icon">&#xe601;</div>

      <%= label_tag 'topic_image_upload' do %>
          <div class="font_icon">
            &#xe600;
          </div>
      <% end %>

      <input id="topic_image_upload" type="file" name="topic_image_upload" data-url="/upload_news_topic_image" multiple>

      <div id="preview_news_topic_btn" class="btn">Preview</div>

      <br>
      <%= f.text_area :context, :placeholder => 'Context' %>

      <div id="preview_news_topic_context"></div>
    </div>
    <div class="field">
      <%= f.check_box :top_news %>
      <%= f.label :top_news %>
    </div>
    <h3>Main Page Display</h3>
    <div>
      <%= f.text_area :short_context, :placeholder => 'Context' %>
      <div id="preview_news_topic_short_context"></div>
    </div>
    </br>
    <div class="actions">
      <%= f.submit f.object.new_record? ? 'Create' : 'Update', :class => 'app_btn' %>
      <%= link_to 'Cancel', news_topics_path, :class => 'btn' %>
    </div>
<% end %>

<script type="text/javascript">
    // auto fill in main page display
    $('#news_topic_context').keyup(function () {
        $('#news_topic_short_context').val($(this).val());
    });

    // Add bold tag event
    $('#text_bold').click(function () {
        var $news_topic_context = $('#news_topic_context');
        var current_context = $news_topic_context.val();

        // Get current position of cursor.
        var selectionStart = $news_topic_context.prop("selectionStart");
        var selectionEnd = $news_topic_context.prop("selectionEnd");

        var new_context = current_context.slice(0, selectionStart) +
                '<b>' + current_context.slice(selectionStart, selectionEnd) + '</b>' +
                current_context.slice(selectionEnd, current_context.length);

        $news_topic_context.val(new_context);
    });

    // by jquery.fileupload.js
    $('#topic_image_upload').fileupload({
        dataType: 'script',
        add: function (e, data) {
            // Append Image uploading tag to news_topic_context.
            var $news_topic_context = $('#news_topic_context');
            var current_context = $news_topic_context.val();

            var selectionStart = $news_topic_context.prop("selectionStart");
            var selectionEnd = $news_topic_context.prop("selectionEnd");

            var new_context = current_context.slice(0, selectionStart) +
                    '![' + data.files[0].name + ']' + current_context.slice(selectionStart, current_context.length);

            $news_topic_context.val(new_context);
//            data.context = $('#news_topic_context').text('Uploading...').appendTo(document.body);
            data.submit();
        }
    });

    $('#preview_news_topic_btn').click(function () {
        if ($(this).hasClass('selected')) {
            $('#preview_news_topic_context').hide();
            $('#news_topic_context').show();
            $('#preview_news_topic_short_context').hide();
            $('#news_topic_short_context').show();
            $(this).removeClass('selected');
        } else {
            $.ajax({
                url: '/preview_news_topic',
                type: "POST",
                data: {
                    news_topic_context: $('#news_topic_context').val(),
                    news_topic_short_context: $('#news_topic_short_context').val()
                },
                dataType: "script",
                success: function () {
                    $('#preview_news_topic_btn').addClass('selected');
                }
            });
        }
    });
</script>

app/views/news_topics/edit.html.erb
<h1>Editing News Topic</h1>

<%= render 'form' %>

app/views/news_topics/index.html.erb
<div id="news_main_content">
  <div id="main_left_content">
    <div class="action">
      <%= link_to '+ News topic', new_news_topic_path %>
    </div>
    <div class="main_left_menu">News</div>
  </div>
  <div id="main_right_content">
    <div id="top_new_panel">
      <div class="header"><b>Top News</b></div>
      <% @top_news.each do |top_news| %>
          <div class="top_news"><%= link_to top_news.title, show_news_topic_path(top_news.id) %></div>
      <% end %>
    </div>
  </div>
  <div id="main_center_content">
    <div id="news_topic_page" class="content">
      <% @news_main_topics.each do |news_topic| %>
          <div class="news_topic" data-topic-id="<%= news_topic.id %>">
            <div class="title">
              <div class="news_topic_title">
                <%= link_to show_news_topic_path(news_topic.id), :class => 'news_topic_link' do %>
                    <b><%= news_topic.title %></b>
                <% end %>
              </div>
              <div class="action">
                <%= link_to '&#xe602'.html_safe, edit_news_topic_path(news_topic.id),
                            :class => 'font_icon' %>
                <%= link_to '&#xe603'.html_safe, news_topic_path(news_topic.id),
                            :method => 'delete', :class => 'font_icon', :data => {:confirm => 'Are you sure?'} %>
              </div>
            </div>
            <div class="creator">
              by <%= news_topic.try('creator').try('name') %> · <%= time_ago_in_words(news_topic.created_at) %> ago
            </div>
            <div class="context"><%= news_topic.short_context.html_safe %></div>
            <div class="news_topic_stats">
              <%= link_to show_news_topic_path(news_topic.id, :state => 'comment'),
                          :class => 'comment_count' do %>
                  <span class="comment font_icon">&#xe605</span>

                  <div class="count comment_count_number"><%= news_topic.comment_count %></div>
              <% end %>
              <span class="like font_icon inactive">&#xe606</span>

              <div class="count inactive"><%= news_topic.like_count %></div>
            </div>
          </div>
      <% end %>
      <div id="infinite_loading"></div>
      <div id="show_next_news_topic">Loading...</div>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    $('#show_next_news_topic').hide();
    $('#content').scroll(function () {
        var $infinite_loading = $('#infinite_loading');
        if ($infinite_loading.length !== 0) {
            if (window.infiniteScroll.isScrolledIntoView('#infinite_loading')) {
                $infinite_loading.remove();
                $('#show_next_news_topic').show();
                var last_news_topic_id = $('.news_topic').last().data('topicId');
                $.getScript('/news_topics/show_more_news_topic/' + last_news_topic_id);
            }
        }
    });

    $('#main_center_content').on('click', '.news_topic', function (e) {
        if (!$(e.target).hasClass('comment') && !$(e.target).hasClass('comment_count_number')
                && !$(e.target).hasClass('font_icon')) {
            $(this).find('.news_topic_link')[0].click();
        }
    });
</script>

app/views/news_topics/new.html.erb
<h1>Create News Topic</h1>
<%= render 'form' %>

app/views/news_topics/preview_news_topic.js.erb
$('#news_topic_context').hide();
$('#news_topic_short_context').hide();
$('#preview_news_topic_context').html('<%=j @news_topic_context.html_safe %>').show();
$('#preview_news_topic_short_context').html('<%=j @news_topic_short_context.html_safe %>').show();

app/views/news_topics/show_more_news_topic.html.erb
<% @news_topics.each do |news_topic| %>
    <div class="news_topic" data-topic-id="<%= news_topic.id %>">
      <div class="title">
        <div class="news_topic_title">
          <%= link_to show_news_topic_path(news_topic.id), :class => 'news_topic_link' do %>
              <b><%= news_topic.title %></b>
          <% end %>
        </div>
        <div class="action">
          <%= link_to '&#xe602'.html_safe, edit_news_topic_path(news_topic.id),
                      :class => 'font_icon' %>
          <%= link_to '&#xe603'.html_safe, news_topic_path(news_topic.id),
                      :method => 'delete', :class => 'font_icon', :data => {:confirm => 'Are you sure?'} %>
        </div>
      </div>
      <div class="creator">
        by <%= news_topic.try('creator').try('name') %> · <%= time_ago_in_words(news_topic.created_at) %> ago
      </div>
      <div class="context"><%= news_topic.short_context.html_safe %></div>
      <div class="news_topic_stats">
        <%= link_to show_news_topic_path(news_topic.id, :state => 'comment'),
                    :class => 'comment_count' do %>
            <span class="comment font_icon">&#xe605</span>

            <div class="count comment_count_number"><%= news_topic.comment_count %></div>
        <% end %>
        <span class="like font_icon inactive">&#xe606</span>

        <div class="count inactive"><%= news_topic.like_count %></div>
      </div>
    </div>
<% end %>
<div id="infinite_loading">Infinite Loading...</div>
<div id="show_next_news_topic">Loading...</div>

app/views/news_topics/show_more_news_topic.js.erb
<% if @news_topics.empty? %>
$('#show_next_news_topic').replaceWith('');
<% else %>
$('#show_next_news_topic').replaceWith(
        '<%=j render :template => 'news_topics/show_more_news_topic', :formats => [:html] %>'
);
<% end %>

app/views/news_topics/upload_news_topic_image.js.erb
<% if @news_topic_image.errors.any? %>

console.log('<%= @news_topic_image.errors.full_messages.to_sentence %>');

<% else %>

var $news_topic_context = $('#news_topic_context');
var news_topic_context = $news_topic_context.val();

news_topic_context = news_topic_context.replace('![<%= @news_topic_image.original_file_name %>]',
        '<div class="news_topic_image"><%=j image_tag @news_topic_image.topic_image.url(:medium),
        :alt => @news_topic_image.original_file_name %></div>');

$news_topic_context.val(news_topic_context);
$('#news_topic_news_main_topic_attributes_context').val($news_topic_context.val());

<% end %>