config/routes.rb
Rails.application.routes.draw do
  resources :news_topic_comments, :only => [:create]
  get 'news_topic_comments/:news_topic_id' => 'news_topic_comments#show_news_topic_comments',
      as: :show_news_topic_comments
  get 'like_news_topic/:news_topic_id' => 'news_topic_comments#like_news_topic', as: :like_news_topic

  get 'news' => 'news_page#index'
  get 'news/:news_topic_id' => 'news_page#show_news_topic', as: :show_news_topic
  get 'show_more_news_topic/:last_topic_id' => 'news_page#show_more_news_topic', as: :show_more_news_topic

  resources :news_topics

  post 'upload_news_topic_image' => 'news_topics#upload_news_topic_image'
  patch 'upload_news_topic_image' => 'news_topics#upload_news_topic_image'
  post 'preview_news_topic' => 'news_topics#preview_news_topic'

  get 'news_topics/show_more_news_topic/:last_topic_id' => 'news_topics#show_more_news_topic',
      as: :news_show_next_topic

  devise_for :users

  root 'news_page#index'

end

app/controllers/news_page_controller.rb
class NewsPageController < ApplicationController

  def index
    @news_topics = NewsTopic.select(
        'id, title, short_context, comment_count, like_count, creator_id, created_at'
    ).includes(:creator).order('id DESC').limit(10)
    @top_news = NewsTopic.select('id, title').top_news.order('id DESC').limit(10)
  end

  def show_more_news_topic
    @news_topics = NewsTopic.select(
        'id, title, short_context, comment_count, like_count, creator_id, created_at'
    ).includes(:creator).where(
        'news_topics.id < ?', params[:last_topic_id].to_i
    ).order('news_topics.id DESC').limit(10)
  end

  def show_news_topic
    @news_topic = NewsTopic.includes(:creator).find(params[:news_topic_id])
    @top_news = NewsTopic.select('id, title').top_news.order('id DESC').limit(10)

    @news_topic_comment = NewsTopicComment.new
  end
end

app/helpers/news_page_helper.rb
module NewsPageHelper
end

app/views/news_page/index.html.erb
<div id="news_main_content">
  <div id="main_left_content">
    <div class="main_left_menu">News</div>
  </div>
  <div id="main_right_content">
    <div id="top_new_panel">
      <div class="header"><b>Top News</b></div>
      <% @top_news.each do |top_news| %>
          <div class="top_news"><%= link_to top_news.title, show_news_topic_path(top_news.id) %></div>
      <% end %>
    </div>
  </div>
  <div id="main_center_content">
    <div class="content">
      <% @news_topics.each do |news_topic| %>
          <div class="news_topic" data-topic-id="<%= news_topic.id %>">
            <div class="title">
              <%= link_to show_news_topic_path(news_topic.id), :class => 'news_topic_link' do %>
                  <b><%= news_topic.title %></b>
              <% end %>
            </div>
            <div class="creator">
              by <%= news_topic.try('creator').try('name') %> · <%= time_ago_in_words(news_topic.created_at) %> ago
            </div>
            <div class="context"><%= news_topic.short_context.html_safe %></div>
            <div class="news_topic_stats">
              <%= link_to show_news_topic_path(news_topic.id, :state => 'comment'),
                          :class => 'comment_count' do %>
                  <span class="comment font_icon">&#xe605</span>

                  <div class="count comment_count_number"><%= news_topic.comment_count %></div>
              <% end %>
              <span class="like font_icon inactive">&#xe606</span>

              <div class="count inactive"><%= news_topic.like_count %></div>
            </div>
          </div>
      <% end %>
      <div id="infinite_loading"></div>
      <div id="show_next_news_topic">Loading...</div>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
    $('#show_next_news_topic').hide();
    $('#content').scroll(function () {
        var $infinite_loading = $('#infinite_loading');
        if ($infinite_loading.length !== 0) {
            if (window.infiniteScroll.isScrolledIntoView('#infinite_loading')) {
                $infinite_loading.remove();
                $('#show_next_news_topic').show();
                var last_news_topic_id = $('.news_topic').last().data('topicId');
                $.getScript('/show_more_news_topic/' + last_news_topic_id);
            }
        }
    });

    $('#main_center_content').on('click', '.news_topic', function (e) {
        if (!$(e.target).hasClass('comment') && !$(e.target).hasClass('comment_count_number')) {
            $(this).find('.news_topic_link')[0].click();
        }
    });
</script>

app/views/news_page/show_more_news_topic.html.erb
<% @news_topics.each do |news_topic| %>
    <div class="news_topic" data-topic-id="<%= news_topic.id %>">
      <div class="title">
        <%= link_to show_news_topic_path(news_topic.id), :class => 'news_topic_link' do %>
            <b><%= news_topic.title %></b>
        <% end %>
      </div>
      <div class="creator">
        by <%= news_topic.try('creator').try('name') %> · <%= time_ago_in_words(news_topic.created_at) %> ago
      </div>
      <div class="context"><%= news_topic.short_context.html_safe %></div>
      <div class="news_topic_stats">
        <%= link_to show_news_topic_path(news_topic.id, :state => 'comment'),
                    :class => 'comment_count' do %>
            <span class="comment font_icon">&#xe605</span>

            <div class="count comment_count_number"><%= news_topic.comment_count %></div>
        <% end %>
        <span class="like font_icon inactive">&#xe606</span>

        <div class="count inactive"><%= news_topic.like_count %></div>
      </div>
    </div>
<% end %>
<div id="infinite_loading">Infinite Loading...</div>
<div id="show_next_news_topic">Loading...</div>

app/views/news_page/show_more_news_topic.js.erb
<% if @news_topics.empty? %>
$('#show_next_news_topic').replaceWith('');
<% else %>
$('#show_next_news_topic').replaceWith(
        '<%=j render :template => 'news_page/show_more_news_topic', :formats => [:html] %>'
);
<% end %>

app/views/news_page/show_news_topic.html.erb
<div id="news_page">
  <div class="news">
    <div class="title"><b><%= @news_topic.title %></b></div>
    <div class="creator">
      by <%= @news_topic.try('creator').try('name') %> · <%= time_ago_in_words(@news_topic.created_at) %> ago
    </div>
    <p class="context">
      <%= @news_topic.context.html_safe %>
    </p>

    <div id="news_topic_stats_<%= @news_topic.id %>" class="news_topic_stats">
      <%= link_to show_news_topic_comments_path(@news_topic.id), :title => 'Show Comments',
                  :class => 'comment_count', :remote => true do %>
          <span class="comment font_icon">&#xe605</span>

          <div class="count"><%= @news_topic.comment_count %></div>
      <% end %>
      <% if current_user %>
          <% if @news_topic.user_liked_this(current_user.id) %>
              <div class="like_count user_liked">
                <span class="like font_icon">&#xe606</span>
              </div>
              <div class="count_like"><%= @news_topic.like_count %></div>
          <% else %>
              <%= link_to like_news_topic_path(@news_topic.id), :class => 'like_count', :remote => true do %>
                  <span class="like font_icon">&#xe606</span>
              <% end %>
              <div class="count_like"><%= @news_topic.like_count %></div>
          <% end %>
      <% else %>
          <div class="like_count">
            <span class="like font_icon">&#xe606</span>
          </div>
          <div class="count_like"><%= @news_topic.like_count %></div>
      <% end %>
      <div class="share_panel">
        <div class="facebook_btn font_icon">&#xe607</div>
        <div class="tweet_btn font_icon">&#xe608</div>
      </div>
    </div>
    <div id="news_comments"></div>
    <% if current_user %>
        <div class="current_user"><b><%= current_user.name %></b></div>
        <div class="news_comment_form"><%= render 'news_topic_comments/form' %></div>
    <% else %>
        <div class="news_comment_form">
          <%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'Register', new_user_registration_path %>
          to post comments
        </div>
    <% end %>
  </div>
  <div id="top_news">
    <div id="top_new_panel">
      <div class="header"><b>Top News</b></div>
      <% @top_news.each do |top_news| %>
          <div class="top_news"><%= link_to top_news.title, show_news_topic_path(top_news.id) %></div>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
    // Show comment
    if ('<%= params[:state] %>' == 'comment') {
        $('.comment_count')[0].click();
        $("#content").animate({ scrollTop: $('.comment_count').offset().top }, 1000);
    }

    // Share News
    $('.facebook_btn').click(function () {
        var title = $('.title b').html();
        var url = 'https://www.facebook.com/sharer/sharer.php?u=<%=j request.original_url %>';
//                '&p[images][0]=' + '<%#= asset_path('logo512.png') %>';
//                '$p[url]=';
        window.open(url, 'facebook_popup', 'width=500,height=300');
    })

    $('.tweet_btn').click(function () {
        var title = $('.title b').html() + '\n';
        var url = 'https://twitter.com/share?url=<%=j request.original_url %>&text=' + title;
        window.open(url, 'tweet_popup', 'width=500,height=300');
    })
</script>