config/routes.rb
Rails.application.routes.draw do
  resources :news_topic_comments, :only => [:create]
  get 'news_topic_comments/:news_topic_id' => 'news_topic_comments#show_news_topic_comments',
      as: :show_news_topic_comments
  get 'like_news_topic/:news_topic_id' => 'news_topic_comments#like_news_topic', as: :like_news_topic

  get 'news' => 'news_page#index'
  get 'news/:news_topic_id' => 'news_page#show_news_topic', as: :show_news_topic
  get 'show_more_news_topic/:last_topic_id' => 'news_page#show_more_news_topic', as: :show_more_news_topic

  resources :news_topics

  post 'upload_news_topic_image' => 'news_topics#upload_news_topic_image'
  patch 'upload_news_topic_image' => 'news_topics#upload_news_topic_image'
  post 'preview_news_topic' => 'news_topics#preview_news_topic'

  get 'news_topics/show_more_news_topic/:last_topic_id' => 'news_topics#show_more_news_topic',
      as: :news_show_next_topic

  devise_for :users

  root 'news_page#index'

end

app/models/news_topic_comment.rb
class NewsTopicComment < ActiveRecord::Base
  belongs_to :news_topic
  belongs_to :creator, :class_name => 'User'

  after_create :count_news_topic_comments

  private
  def count_news_topic_comments
    news_topic = self.news_topic
    news_topic.update_attribute(:comment_count, news_topic.news_topic_comments.count)
  end
end

app/controllers/news_topic_comments_controller.rb
class NewsTopicCommentsController < ApplicationController
  before_action :set_news_topic_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show_news_topic_comments]

  def show_news_topic_comments
    @news_topic_comments = NewsTopicComment.includes(:creator).where(
        'news_topic_id = ?', params[:news_topic_id]
    ).order('id')
  end

  def like_news_topic
    news_topic_user_like = NewsTopicUserLike.new
    news_topic_user_like.news_topic_id = params[:news_topic_id]
    news_topic_user_like.user_id = current_user.id

    if news_topic_user_like.save
      @news_topic = NewsTopic.select('id, like_count').find(params[:news_topic_id])
    end
  end

  # GET /news_topic_comments/1/edit
  def edit
  end

  # POST /news_topic_comments
  # POST /news_topic_comments.json
  def create
    @news_topic_comment = NewsTopicComment.new(news_topic_comment_params)
    @news_topic_comment.creator_id = current_user.id
    @news_topic_comment.creator_ip = current_user.current_sign_in_ip

    respond_to do |format|
      if @news_topic_comment.save
        @news_topic_comments = NewsTopicComment.where(
            'news_topic_id = ?', @news_topic_comment.news_topic_id
        ).order('id')

        format.js { render :show_news_topic_comments }
        # format.html { redirect_to @news_topic_comment, notice: 'News topic comment was successfully created.' }
        # format.json { render :show, status: :created, location: @news_topic_comment }
      else
        # format.html { render :new }
        # format.json { render json: @news_topic_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_topic_comments/1
  # PATCH/PUT /news_topic_comments/1.json
  def update
    respond_to do |format|
      if @news_topic_comment.update(news_topic_comment_params)
        format.html { redirect_to @news_topic_comment, notice: 'News topic comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_topic_comment }
      else
        format.html { render :edit }
        format.json { render json: @news_topic_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_topic_comments/1
  # DELETE /news_topic_comments/1.json
  def destroy
    @news_topic_comment.destroy
    respond_to do |format|
      format.html { redirect_to news_topic_comments_url, notice: 'News topic comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_news_topic_comment
    @news_topic_comment = NewsTopicComment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def news_topic_comment_params
    params.require(:news_topic_comment).permit(:news_topic_id, :context)
  end
end

app/helpers/news_topic_comments_helper.rb
module NewsTopicCommentsHelper
end

app/views/news_topic_comments/_form.html.erb
<%= form_for(@news_topic_comment, :remote => true) do |f| %>
    <% if @news_topic_comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@news_topic_comment.errors.count, "error") %> prohibited this news_topic_comment from being
            saved:</h2>

          <ul>
            <% @news_topic_comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= f.hidden_field :news_topic_id, :value => @news_topic.id %>

    <div class="field">
      <%= f.text_area :context, :placeholder => 'Comment' %>
    </div>
    <div class="actions">
      <%= f.submit 'Post', :class => 'app_btn' %>
    </div>
<% end %>

<script type="text/javascript" charset="utf-8">
    $('.app_btn[type="submit"]').attr('disabled', 'disabled');

    $('#news_topic_comment_context').keyup(function () {
        if ($.trim($(this).val()) === '') {
            $('.app_btn[type="submit"]').attr('disabled', 'disabled');
        } else {
            $('.app_btn[type="submit"]').removeAttr('disabled');
        }
    });

    $('#new_news_topic_comment').bind('ajax:complete', function () {
        $('#news_topic_comment_context').val('');
        $('.app_btn[type="submit"]').attr('disabled', 'disabled');
        $("#content").animate({ scrollTop: $('#content').find('.center').height() }, 1000);
    });
</script>

app/views/news_topic_comments/edit.html.erb
<h1>Editing news_topic_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_topic_comment %> |
<%= link_to 'Back', news_topic_comments_path %>

app/views/news_topic_comments/like_news_topic.js.erb
<% if @news_topic %>
var $news_topic = $('#news_topic_stats_<%= @news_topic.id %>');
$news_topic.find('.like_count').replaceWith(
        '<div class="like_count user_liked"><span class="like font_icon">&#xe606</span></div>'
);

$news_topic.find('.count_like').html('<%= @news_topic.like_count %>');
<% end %>

app/views/news_topic_comments/show_news_topic_comments.html.erb
<% @news_topic_comments.each do |news_topic_comment| %>
    <div class="comment" data-id="<%= news_topic_comment.id %>">
      <div class="comment_creator">
        <b class="name"><%= news_topic_comment.creator.name %></b>
        <span class="created_at"><%= time_ago_in_words(news_topic_comment.created_at) %> ago</span>
      </div>
      <div class="comment_context"><%= news_topic_comment.context %></div>
    </div>
<% end %>

app/views/news_topic_comments/show_news_topic_comments.js.erb
var $comment_count = $('.comment_count');
$comment_count.addClass('selected');
$comment_count.find('.count').html('<%= @news_topic_comments.length %>');

$('#news_comments').html(
        '<%=j render :template => 'news_topic_comments/show_news_topic_comments', :formats => [:html] %>'
);