config/routes.rb
Rails.application.routes.draw do
  resources :news_topic_comments, :only => [:create]
  get 'news_topic_comments/:news_topic_id' => 'news_topic_comments#show_news_topic_comments',
      as: :show_news_topic_comments
  get 'like_news_topic/:news_topic_id' => 'news_topic_comments#like_news_topic', as: :like_news_topic

  get 'news' => 'news_page#index'
  get 'news/:news_topic_id' => 'news_page#show_news_topic', as: :show_news_topic
  get 'show_more_news_topic/:last_topic_id' => 'news_page#show_more_news_topic', as: :show_more_news_topic

  resources :news_topics

  post 'upload_news_topic_image' => 'news_topics#upload_news_topic_image'
  patch 'upload_news_topic_image' => 'news_topics#upload_news_topic_image'
  post 'preview_news_topic' => 'news_topics#preview_news_topic'

  get 'news_topics/show_more_news_topic/:last_topic_id' => 'news_topics#show_more_news_topic',
      as: :news_show_next_topic

  devise_for :users

  root 'news_page#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moving Limes</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= content_for?(:head) ? yield(:head) : '' %>
</head>
<body>

<header>
  <div class="center">
    <div id="h_l">
      <%= link_to root_path do %>
          <%= image_tag 'logo.png', :class => 'header_logo' %> <span>Moving Limes</span>
      <% end %>
    </div>

    <ul id="h_menu">
    <!--<li class="nev_menu">-->
    <!--<%#= link_to 'News', news_topics_path, :class => ('selected' if params[:controller] == 'news_topics') %>-->
    <!--</li>-->
    <!--<li class="nev_menu">Movies</li>-->
    <!--<li class="nev_menu">Series</li>-->
      <% if current_user && current_user.role == User::ADMIN_USER %>
        <li class="nev_menu"><%= link_to 'Edit News', news_topics_path %></li>
      <% end %>
    </ul>

    <div id="h_r">
      <% if current_user %>
          <div id="user_display_name"><%= current_user.name %></div>
          <div id="user_info_panel">
            <div class="name"><b><%= current_user.name %></b></div>
            <div class="email"><%= current_user.email %></div>
            <div class="action">
              <%= link_to 'Edit', edit_user_registration_path, :class => 'btn' %>
              <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', :class => 'btn sign_out_btn' %>
            </div>
          </div>
      <% else %>
          <%= link_to "Sign in", new_user_session_path, :id => 'user_sign_in' %>
      <% end %>
    </div>
  </div>
</header>

<div id="content">
  <div class="center">
    <%= yield %>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
    window.users.showUserInfoPanel();
</script>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moving Limes</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="session_center">
    <%= yield %>
</div>

</body>
</html>